# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Readignore < Formula
  desc ".gitignore for AI coding agents — declare files your AI agent must not read."
  homepage "https://github.com/0xByteBard404/readignore"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xByteBard404/readignore/releases/download/v0.6.0/readignore_0.6.0_darwin_amd64.tar.gz"
      sha256 "ff42ac1ca49f1ae0470b2305f4189a7842ce14d7678dfa606e24fee9af54fd0e"

      define_method(:install) do
        bin.install "readignore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xByteBard404/readignore/releases/download/v0.6.0/readignore_0.6.0_darwin_arm64.tar.gz"
      sha256 "a0f478bb481e40106dbff35e8493202283e26818056d77b3aecf278a3b798598"

      define_method(:install) do
        bin.install "readignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xByteBard404/readignore/releases/download/v0.6.0/readignore_0.6.0_linux_amd64.tar.gz"
      sha256 "b83a92c995405b3af0d75a0dacb16c6d5a69b085a670714da2838146b984ae0b"
      define_method(:install) do
        bin.install "readignore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xByteBard404/readignore/releases/download/v0.6.0/readignore_0.6.0_linux_arm64.tar.gz"
      sha256 "a9305cc2f0f1c5558886c1bbb0735fc9df79fba565a98404f34bfc6aef586f2a"
      define_method(:install) do
        bin.install "readignore"
      end
    end
  end

  test do
    system "#{bin}/readignore", "--version"
  end
end
