# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Readignore < Formula
  desc ".gitignore for AI coding agents — declare files your AI agent must not read."
  homepage "https://github.com/0xByteBard404/readignore"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xByteBard404/readignore/releases/download/v0.7.0/readignore_0.7.0_darwin_amd64.tar.gz"
      sha256 "70bb1d09d18a6b66694feed1d803332193b557f7fe3d0b49d05149d089cca747"

      define_method(:install) do
        bin.install "readignore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xByteBard404/readignore/releases/download/v0.7.0/readignore_0.7.0_darwin_arm64.tar.gz"
      sha256 "475ff9e7b6f7f08f7cbd56f7c0a7f2faf9c75f84166f1ac8d5e8fe10dd51a2fb"

      define_method(:install) do
        bin.install "readignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xByteBard404/readignore/releases/download/v0.7.0/readignore_0.7.0_linux_amd64.tar.gz"
      sha256 "9c13165cf67ceba0644bbac81e2edae2fdeb10db083fe0c59ee46a14276ef51b"
      define_method(:install) do
        bin.install "readignore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xByteBard404/readignore/releases/download/v0.7.0/readignore_0.7.0_linux_arm64.tar.gz"
      sha256 "95e163f516cc5c8fa3f7ef9d3562e1c70af1d47a3450740accb2c4d72735eebe"
      define_method(:install) do
        bin.install "readignore"
      end
    end
  end

  test do
    system "#{bin}/readignore", "--version"
  end
end
